name: DemoSanofi

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  buildSanofi:    
    runs-on: ubuntu-latest
    
    steps:    
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 12.x
